### ISSUE TITLE
What are the intended OSs/versions supported? dependencies?

### ISSUE THREAD

**Issue by CesarSolis** [microsoft/latte#3]
![image](https://user-images.githubusercontent.com/8282360/139304308-7c2e80b5-86a0-4758-bf56-5cb8b3489c5d.png)

Got error when executing in WS2012 R2: The program can't start because
api-ms-win-core-libraryloader-I1-2-1.dll is missing from your computer. Try reinstalling the program to fix this problem.

**Comment by maolson-msft** [comment]
Should be addressed by https://github.com/microsoft/latte/releases/tag/v1.0.0, which is built for OS versions down to Win7.
